<xsl:stylesheet version="1.0"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:l="http://docbook.sourceforge.net/xmlns/l10n/1.0"
		xmlns:h="http://www.w3.org/1999/xhtml"
		xmlns="http://www.w3.org/1999/xhtml"
		exclude-result-prefixes="h l">

  <!-- Stylesheet containing all htmlbook-xsl params, and their default values -->

  <xsl:output method="xml"
              encoding="UTF-8"/>
  <xsl:preserve-space elements="*"/>

  <xsl:param name="autogenerate-toc" select="1"/>
  <xsl:param name="autogenerate-index" select="1"/>

  <xsl:param name="book-language">
    <xsl:choose>
      <xsl:when test="//h:html[@lang != '']|//h:body[@lang != '']">
	<xsl:value-of select="(//h:html[@lang != '']|//h:body[@lang != ''])[1]"/>
      </xsl:when>
      <xsl:otherwise>
	<xsl:text>en</xsl:text>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:param>

  <xsl:param name="localizations-dir" select="'localizations/'"/>

  <xsl:param name="localizations">
    <xsl:variable name="localizations-file">
      <xsl:value-of select="concat($localizations-dir, $book-language, '.xml')"/>
    </xsl:variable>
    <xsl:choose>
      <!-- If $localizations-file is valid, use it... -->
      <xsl:when test="document($localizations-file)//l:l10n">
	<xsl:copy-of select="document($localizations-file)"/>
      </xsl:when>
      <!-- Otherwise default to "en" (English) -->
      <xsl:otherwise>
	<xsl:copy-of select="document($localizations-dir, 'en', '.xml')"/>
	<xsl:message><xsl:value-of select="document($localizations-dir, 'en', '.xml')"/></xsl:message>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:param>

  <!-- Index-specific params -->
  <xsl:param name="autogenerate-index" select="1"/>

  <xsl:param name="index.on.role" select="0"/>

  <xsl:param name="index.on.type" select="0"/>

  <xsl:param name="index.links.to.section" select="0"/>

  <xsl:param name="index.term.separator"/>

  <xsl:param name="index.number.separator"/>

  <xsl:param name="index.range.separator"/>

  <!-- Specify whether or not to overwrite any content in the index placeholder element -->
  <xsl:param name="index-placeholder-overwrite-contents" select="0"/>

  <!-- TOC-specific params -->
  <xsl:param name="autogenerate-toc" select="1"/>

  <!-- Specify whether or not to overwrite any content in the TOC placeholder element -->
  <xsl:param name="toc-placeholder-overwrite-contents" select="0"/>

  <!-- Specify whether or not to include book title in autogenerated TOC -->
  <xsl:param name="toc-include-title" select="0"/>

  <!-- Specify whether to include number labels in TOC entries -->
  <xsl:param name="toc-include-labels" select="0"/>

</xsl:stylesheet> 
